# Generated by Django 5.2.1 on 2025-07-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_littleheart', '0017_delete_calendarevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
