# Generated by Django 5.2.1 on 2025-07-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_littleheart', '0019_groomingbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groomingbooking',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('canceled', 'Canceled')], default='approved', max_length=10),
        ),
    ]
