# Generated by Django 5.2.2 on 2025-07-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_littleheart', '0021_alter_groomingbooking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groomingbooking',
            name='email',
            field=models.EmailField(default='littleheartpetshop@gmail.com', max_length=50),
        ),
    ]
