# Generated by Django 5.2.2 on 2025-07-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_littleheart', '0022_alter_groomingbooking_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='groomingbooking',
            name='user',
        ),
        migrations.AlterField(
            model_name='groomingbooking',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
