# Generated by Django 5.2.2 on 2025-07-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_littleheart', '0023_remove_blog_author_remove_groomingbooking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groomingbooking',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
