# Generated by Django 5.2.2 on 2025-07-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_unifiedbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unifiedbooking',
            name='pet_size',
        ),
        migrations.AddField(
            model_name='unifiedbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
