# Generated by Django 5.2.2 on 2025-07-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_remove_unifiedbooking_pet_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedbooking',
            name='pet_size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=10, null=True),
        ),
    ]
