# Generated by Django 5.2.2 on 2025-07-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_unifiedbooking_pet_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedbooking',
            name='estimated_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
