# Generated by Django 5.2.2 on 2025-07-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0010_unifiedbooking_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedbooking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
